package rompecabezas;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import pieza.PiezaRompeCabezas;
import utils.Constantes;

public class Formulario extends javax.swing.JFrame {
    private static PiezaRompeCabezas arrayPiezas[];
    private Controlador controlador;

    public Formulario() {
        initComponents();
        this.setTitle("Rompecabezas");
        jButtonTerminar.setEnabled(false);
        iniciarTablero();
    }

    private void iniciarTablero() {
        controlador = new Controlador();
        arrayPiezas = new PiezaRompeCabezas[Constantes.FILAS * Constantes.COLUMNAS];
        int[] posiciones = controlador.getPosicionFinal();
        int i = 0;
        while (i < 9) {
            Icon imagen;
            if (posiciones[i] == -1) {//Si es la primer pieza es la vacia le asigno orden -1 y la imagen vacia
                imagen = new ImageIcon(getClass().getResource("/imagenesPiezas/vacio.jpg"));
            } else {
                imagen = new ImageIcon(getClass().getResource("/imagenesPiezas/" + posiciones[i] + ".jpg"));
            }
            arrayPiezas[i] = new PiezaRompeCabezas(imagen);
            arrayPiezas[i].setOrder(posiciones[i]);
            arrayPiezas[i].addMouseListener(controlador);
            jPanelTablero.setSize(600, 450);
            jPanelTablero.setLayout(new java.awt.GridLayout(Constantes.FILAS, Constantes.COLUMNAS, 0, 0));
            this.jPanelTablero.add(arrayPiezas[i]);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablero = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(652, 600));

        javax.swing.GroupLayout jPanelTableroLayout = new javax.swing.GroupLayout(jPanelTablero);
        jPanelTablero.setLayout(jPanelTableroLayout);
        jPanelTableroLayout.setHorizontalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jPanelTableroLayout.setVerticalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonTerminar.setText("Terminar");
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButtonNuevo)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonTerminar)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonTerminar))
                .addGap(31, 31, 31)
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        controlador.nuevoJuego(arrayPiezas, this);
        jButtonNuevo.setEnabled(false);
        jButtonTerminar.setEnabled(true);
        controlador.setHabilitarTablero(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        jButtonTerminar.setEnabled(false);
        controlador.setTerminarJuego(true);
        controlador.setHabilitarTablero(false);
        jButtonNuevo.setEnabled(true);
        for (int i = 0; i < controlador.getPosicionFinal().length; i++) {
            this.jPanelTablero.remove(arrayPiezas[i]);
        }
        this.jPanelTablero.revalidate();
        iniciarTablero();
    }//GEN-LAST:event_jButtonTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame=   new Formulario();
                frame.setLocationRelativeTo(null);//centra la ventana en medio de la pantalla
                frame.setVisible(true);
            }
        });
    }

    public void setEnabledNuevo(Boolean enabled) {
        jButtonNuevo.setEnabled(enabled);
    }

    public void setEnabledTerminar(Boolean enabled) {
        jButtonTerminar.setEnabled(enabled);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JPanel jPanelTablero;
    // End of variables declaration//GEN-END:variables
}
